/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndksetup_JNIwithHeaderFile */

#ifndef _Included_com_example_ndksetup_JNIwithHeaderFile
#define _Included_com_example_ndksetup_JNIwithHeaderFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndksetup_JNIwithHeaderFile
 * Method:    squared
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndksetup_JNIwithHeaderFile_squared
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
